### ISSUE TITLE
要望: 読みを伸び縮みさせるためのキーアサインの設定機能

### ISSUE THREAD

**Issue by ShikiOkasaka** [deton/tsf-tutcode#12]
要望です。読みを伸び縮みさせるためのキーアサイン<と>も、たとえばカーソルキーなどに設定できるようになると嬉しいです。
https://github.com/deton/tsf-tutcode/blob/master/imcrvtip/KeyHandlerChar.cpp#L18-L35

**Comment by deton** [comment]
ひとまず、読みの伸び縮めをカーソルキーでもできるようにするだけにしました。 #13 

現状のtsf-tutcodeの内部処理では、
カーソルキーを左右移動機能に設定していると、
同じカーソルキーを別の機能に割り当てる設定をしても効かないので。
(つまり、カーソルキーを読みの伸び縮め機能に使うように設定すると、
カーソルキーを左右移動機能に設定しないようにする必要があって、
そうすると前置型読み入力中等でのカーソルキーによる左右移動ができなくなる)

いったんクローズします。
読みの伸び縮め用のキーアサインを設定する機能が欲しい場合は再オープンしてください。

## 対応方法案
* 現状の内部処理: 設定されたキーによって場合分けして、アサインされた機能を実行。
  機能実行時に候補表示中モードかどうかを判定して処理。
  (現状は、グローバルなキーマップのみ持っている形)
 1. 押されたキーが左カーソルキーかの判定→左移動機能
 1. 押されたキーが右カーソルキーかの判定→右移動機能
* 対応方法案: 候補表示中モードかどうかの判定を先にして、
  機能によって場合分けして、アサインされたキーかどうかを判定
 1. 左移動機能を実行するかの判定→押されたキーが左カーソルキー?
 1. 右移動機能を実行するかの判定→押されたキーが右カーソルキー?
