### ISSUE TITLE
Visual Studio Community 2013を用いたビルドについて

### ISSUE THREAD

**Issue by kozo2** [deton/tsf-tutcode#3]
Visual Studio Community 2013を(ATL用に)MFCありでインストールして、PlatformToolsetをv120にしてビルドを試みた際に下記リンクのエラーが出ました。

https://gist.github.com/kozo2/ac8c5cf6e28427213a01

もし何かご助言をいただけるようであればお願いいたします。

**Comment by deton** [comment]
commit 25426dd で修正しました。
(なお、Debugビルドは使っていません。動作も未確認です)

**Comment by kozo2** [comment]
ありがとうございます。
Visual Studio Community 2013を用いたビルドに成功しました。
