### ISSUE TITLE
README.md中の開発環境を用いたmsi installer作成までのdocument

### ISSUE THREAD

**Issue by kozo2** [deton/tsf-tutcode#5]
https://twitter.com/deton_kih/status/565135239144415233

でVS2013でのbuild方法の概要をお教えいただいたのですがinstallerがもしtsf-tutcodeの利用に必要であれば伺いたいです。
もしinstallerが必ずしも要るわけではないようであればその場合の利用方法を伺いたいです

**Comment by deton** [comment]
Visual Studio Community 2015では未確認ですが、
WiX Toolsetをインストールしてあれば、
ソリューションのビルドをすればmsiインストーラもビルドされます。
(build.batでも同じ)

installer無しでも、installer/tsftutcode-x86.wxsと同様の作業を行えば、
インストールは可能だと思いますが、試したことは無いです。

インストール済の環境に、新たにビルドしたexe等を動作確認のため上書きするのは
よくやるので、inst32.batというバッチファイルを使っています。
git addしておきました。

**Comment by kozo2** [comment]
inst32.batのご追加ありがとうございました。

Visual Studio Community 2015でのPlatformToolsetの指定がわからず
またかつてVisual Studio Community 2013で行ったその方法も思い出せなかったため
当初のissue題を
「detonさんの開発環境と同じ環境を構築しそこからmsiファイルを作ること」に変更しました。

**Comment by deton** [comment]
PlatformToolsetのv120への変更と、READMEの開発環境のVS2013への変更を行いました。
これでVS2013+WiXでビルドすればmsiファイルができるはずです。

**Comment by kozo2** [comment]
ありがとうございます。
おかげさまでmsiファイルの作成ができました。
手順を記したドキュメントのパッチを送らせて頂いた後で
本issueはcloseさせていただこうと思います。
