### ISSUE TITLE
AppVeyorを用いたContinuous Integration

### ISSUE THREAD

**Issue by kozo2** [deton/tsf-tutcode#7]
http://www.appveyor.com/docs/installed-software

を見た感じ実現できそうに思ったのでとりあえずissueだけさせていただきます。
後でappveyor.ymlのpull requestを送らせていただくかもしれません。

**Comment by kozo2** [comment]
x64 buildでうまくいかない点の解決ができなかったのですが #8 でpull requestさせていただきました

**Comment by deton** [comment]
複数行のコマンドが1行とみなされていてエラーになっていたので修整の上マージしました。

**Comment by kozo2** [comment]
ありがとうございました。
おかげさまで x64 build の方も問題なくなりました
https://ci.appveyor.com/project/kozo2/tsf-tutcode/build/1.0.11
